-- AlterTable
ALTER TABLE "expenses" ALTER COLUMN "currency_quote" SET DEFAULT 1,
ALTER COLUMN "currency_quote" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "expense_value" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "total_converted" SET DATA TYPE DOUBLE PRECISION;
